import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/Layout'
export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>DBWT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href='../images/DBWT.png' />
      </Head>  
    </div>
  )
}
